// Copyright 2020-present Genki contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export class NodeKeys {
    static Alignment = "Alignment"
    static AlphaB = "B"
    static AlphaG = "G"
    static AlphaR = "R"
    static AlphaX = "X"
    static AlphaY = "Y"
    static Amount = "Amount"
    static Animated = "Animated"
    static Animations = "Animations"
    static Asset = "Asset"
    static Audio = "Audio"
    static Background = "Background"
    static Blend = "Blend"
    static Brightness = "Brightness"
    static Child = "Child"
    static Color = "Color"
    static ColorAlpha = "Alpha"
    static ColorBlue = "Blue"
    static ColorGreen = "Green"
    static ColorRed = "Red"
    static Content = "Content"
    static Contrast = "Contrast"
    static CornerRadius = "Corner Radius"
    static Data = "Data"
    static Delay = "Delay"
    static Delimiter = "|"
    static Dimensions = "Dimensions"
    static Direction = "Direction"
    static DropShadow = "Shadow"
    static DropShadowOffset = "Shadow Offset"
    static DropShadowColor = "Shadow Color"
    static Ducking = "Ducking"
    static Duration = "Duration"
    static Effects = "Effects"
    static Ellipsize = "Ellipsize"
    static End = "End"
    static FadeIn = "Fade In"
    static FadeOut = "Fade Out"
    static File = "File"
    static Filters = "Filters"
    static FitHeight = "Fit Height"
    static FitWidth = "Fit Width"
    static Focus = "Focus"
    static Font = "Font"
    static FontSize = "Font Size"
    static Fullscreen = "Fullscreen"
    static Gradient = "Gradient"
    static GradientStart = "Gradient Start"
    static GradientEnd = "Gradient End"
    static GradientMode = "Gradient Mode"
    static Gravity = "Gravity"
    static Image = "Image"
    static In = "In"
    static Index = "Index"
    static Inner = "Inner"
    static Integer = "Integer"
    static Intensity = "Intensity"
    static ItemName = "Name"
    static Kerning = "Kerning"
    static Kind = "Kind"
    static Layout = "Layout"
    static Leading = "Leading"
    static Margin = "Margin"
    static Matte = "Matte"
    static Metadata = "Metadata"
    static Multiline = "Multiline"
    static Offset = "Offset"
    static Opacity = "Opacity"
    static Operator = "Operator"
    static Out = "Out"
    static Outer = "Outer"
    static OutlineWidth = "Outline Width"
    static OutlineColor = "Outline Color"
    static Output = "Output"
    static Parent = "Parent"
    static Position = "Position"
    static Resizable = "Resizable"
    static Result = "Result"
    static Return = "Return"
    static Rotation = "Rotation"
    static Saturation = "Saturation"
    static Scalar = "Scalar"
    static Scale = "Scale"
    static ScaleStart = "Scale Start"
    static ScaleEnd = "Scale End"
    static ScreenRect = "Screen Rect"
    static SizeRange = "Size Range"
    static SmoothEdges = "Smooth Edges"
    static Spread = "Spread"
    static Start = "Start"
    static Step = "Step"
    static Text = "Text"
    static Timing = "Timing"
    static TransitionStart = "Transition Start"
    static TransitionEnd = "Transition End"
    static Trim = "Trim"
    static TrimDuration = "Trim Duration"
    static TrimStart = "Trim Start"
    static Untitled = "Untitled"
    static Value = "Value"
    static ValueA = "Value A"
    static ValueB = "Value B"
    static Video = "Video"
    static Visible = "Visible"
    static Volume = "Volume"
    static ZOrder = "Z-Order"
    static ZOrderBegin = "Z Begin"
    static ZOrderEnd = "Z End"

    static GroupAppearance = "Appearance"
    static GroupAudio = "Audio"
    static GroupGeometry = "Geometry"
    static GroupGradient = "Gradient"
    static GroupMetrics = "Metrics"
    static GroupNone = ""
    static GroupOutline = "Outline"
    static GroupShadow = "Shadow"
    static GroupStep = "Step"
    static GroupTiming = "Timing"
    static GroupTransform = "Transform"
    static GroupTrim = "Trim"
}